---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/gce-cpi-release
inputs:
  - name: bosh-cpi-src
  - name: ci
  - name: bosh-cpi-release
  - name: bosh-deployment
  - name: stemcell
  - name: bosh-cli
  - name: infrastructure
outputs:
  - name: deployment
  - name: director-creds
run:
  path: ci/ci/tasks/setup-director.sh
params:
  BOSH_INIT_LOG_LEVEL:            warn
  google_subnetwork_range:        replace-me
  private_key_user:               replace-me
  private_key_data:               replace-me
  google_json_key_data:           replace-me
