---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/gce-cpi-release
inputs:
  - name: bosh-cpi-src
  - name: ci
run:
  path: ci/ci/tasks/setup-infrastructure.sh
params:
  google_project:                 replace-me
  google_region:                  replace-me
  google_zone:                    replace-me
  google_json_key_data:           replace-me
  google_auto_network:            replace-me
  google_network:                 replace-me
  google_subnetwork:              replace-me
  google_subnetwork_range:        replace-me
  google_firewall_internal:       replace-me
  google_firewall_external:       replace-me
  google_address_director:        replace-me
  google_address_bats:            replace-me
  google_target_pool:             replace-me
  google_backend_service:         replace-me
  google_region_backend_service:  replace-me
  google_address_int:             replace-me
  google_service_account:         replace-me
