---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/gce-cpi-release
inputs:
  - name: bosh-cpi-src
  - name: bosh-cli
  - name: deployment
  - name: infrastructure
  - name: director-creds
run:
  path: ci/ci/tasks/teardown-director.sh
params:
  BOSH_INIT_LOG_LEVEL: warn
  google_json_key_data:           replace-me
  private_key_user:               replace-me
  private_key_data:               replace-me
